version: '3'
services:
  orientdb:
    image: orientdb:2.2.30
    command: server.sh
    ports:
      - "127.0.0.1:2480:2480"
      - "127.0.0.1:2424:2424"
    environment:
      ORIENTDB_ROOT_PASSWORD: root
  postgres:
    image: postgres:10.5
    restart: always
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - "127.0.0.1:5432:5432"
  mysql:
    image: mysql:8.0.11
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  mariadb:
    image: mariadb:10.3.11
    restart: always
    ports:
      - "127.0.0.1:3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    restart: always
    ports:
      - "127.0.0.1:1433:1433"
    environment:
      ACCEPT_EULA: "yes"
      MSSQL_SA_PASSWORD: Root-secure1  # password requirements are more stringent for MSSQL image
