version: '3'
services:
  orientdb:
    image: orientdb:2.2.30
    command: server.sh
    ports:
      - "127.0.0.1:2481:2480"
      - "127.0.0.1:2425:2424"
    environment:
      ORIENTDB_ROOT_PASSWORD: root
  postgres:
    image: postgres:10.5
    restart: always
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - "127.0.0.1:5433:5432"
  mysql:
    image: mysql:8.0.11
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "127.0.0.1:3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  mariadb:
    image: mariadb:10.3.11
    restart: always
    ports:
      - "127.0.0.1:3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    restart: always
    ports:
      - "127.0.0.1:1434:1433"
    environment:
      ACCEPT_EULA: "yes"
      MSSQL_SA_PASSWORD: Root-secure1  # password requirements are more stringent for MSSQL image
  neo4j:
    image: neo4j:3.5.6
    restart: always
    ports:
      - "127.0.0.1:7475:7474"
      - "127.0.0.1:7688:7687"
    environment:
      NEO4J_AUTH: neo4j/root
  redisgraph:
    image: redislabs/redisgraph:1.2.2
    restart: always
    ports:
      - "127.0.0.1:6380:6379"
