name: Test and lint Python package

on:
  push:
    branches:
      - "*"
    tags:
      - "v*"
  pull_request:
    branches:
      - "*"
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install binary dependencies
        run: |
          bash -c "wget -qO- https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -"
          sudo add-apt-repository "$(wget -qO- https://packages.microsoft.com/config/ubuntu/"$(lsb_release -r -s)"/prod.list)"
          sudo apt-get update
          sudo apt-get install unixodbc-dev python-mysqldb libmysqlclient-dev
          ACCEPT_EULA=Y sudo apt-get install msodbcsql17
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools pipenv
          pipenv install --dev --deploy --system
          pip install -e .
      - name: Run lint checks
        run: |
          ./scripts/copyright_line_check.sh
          ./scripts/lint.sh
  tests:
    runs-on: ubuntu-latest
    services:
      orientdb:
        image: orientdb:2.2.30
        ports:
          - "127.0.0.1:2480:2480"
          - "127.0.0.1:2424:2424"
        env:
          ORIENTDB_ROOT_PASSWORD: root
      postgres:
        image: postgres:10.5
        env:
          POSTGRES_PASSWORD: root
        ports:
          - "127.0.0.1:5432:5432"
      mysql:
        image: mysql:8.0.11
        ports:
          - "127.0.0.1:13306:3306"
        env:
          MYSQL_ROOT_PASSWORD: root
      mariadb:
        image: mariadb:10.3.11
        ports:
          - "127.0.0.1:13307:3306"
        env:
          MYSQL_ROOT_PASSWORD: root
      mssql:
        image: mcr.microsoft.com/mssql/server:2017-latest
        ports:
          - "127.0.0.1:1433:1433"
        env:
          ACCEPT_EULA: "yes"
          MSSQL_SA_PASSWORD: Root-secure1  # password requirements are more stringent for MSSQL image
      neo4j:
        image: neo4j:3.5.6
        ports:
          - "127.0.0.1:7474:7474"
          - "127.0.0.1:7687:7687"
        env:
          NEO4J_AUTH: neo4j/root
      redisgraph:
        image: redislabs/redisgraph:1.2.2
        ports:
          - "127.0.0.1:6379:6379"
    strategy:
      max-parallel: 3
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install binary dependencies
        run: |
          bash -c "wget -qO- https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -"
          sudo add-apt-repository "$(wget -qO- https://packages.microsoft.com/config/ubuntu/"$(lsb_release -r -s)"/prod.list)"
          sudo apt-get update
          sudo apt-get install unixodbc-dev python-mysqldb libmysqlclient-dev
          ACCEPT_EULA=Y sudo apt-get install msodbcsql17
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools pipenv
          pipenv install --dev --deploy --system
          pip install -e .
      - name: Test with pytest
        run: |
          pytest --cov=graphql_compiler graphql_compiler/tests
          codecov
