name: Test and lint Python package

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - "*"
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install binary dependencies
        run: |
          bash -c "wget -qO- https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -"
          sudo add-apt-repository "$(wget -qO- https://packages.microsoft.com/config/ubuntu/"$(lsb_release -r -s)"/prod.list)"
          sudo apt-get update
          sudo apt-get install unixodbc-dev python-mysqldb libmysqlclient-dev
          ACCEPT_EULA=Y sudo apt-get install msodbcsql17
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools pipenv
          pipenv install --dev --deploy --system
          pip install -e .
      - name: Run lint checks
        run: |
          pipenv run ./scripts/copyright_line_check.sh
          pipenv run ./scripts/lint.sh
  tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install binary dependencies
        run: |
          bash -c "wget -qO- https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -"
          sudo add-apt-repository "$(wget -qO- https://packages.microsoft.com/config/ubuntu/"$(lsb_release -r -s)"/prod.list)"
          sudo apt-get update
          sudo apt-get install unixodbc-dev python-mysqldb libmysqlclient-dev
          ACCEPT_EULA=Y sudo apt-get install msodbcsql17
      - name: Start database docker containers
        run: |
          docker-compose up -d
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools pipenv
          pipenv install --dev --deploy --system
          pip install -e .
      - name: Test with pytest
        run: |
          pytest --cov=graphql_compiler graphql_compiler/tests
          codecov
